export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL  =    'ADD_POST_FAIL';

export const POST_ALL_REQUEST =  'POST_ALL_REQUEST';
export const POST_ALL_SUCCESS =  'POST_ALL_SUCCESS';
export const POST_ALL_FAIL   =   'POST_ALL_FAIL';

export const POST_DELETE_REQUEST =  'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS =  'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL   =   'POST_DELETE_FAIL';

export const POST_ADD_LIKE_REQUEST =  'POST_ADD_LIKE_REQUEST';
export const POST_ADD_LIKE_SUCCESS =  'POST_ADD_LIKE_SUCCESS';
export const POST_ADD_LIKE_FAIL   =   'POST_ADD_LIKE_FAIL';
export const POST_ADD_LIKE_RESET   =   'POST_ADD_LIKE_RESET';

export const POST_UNLIKE_REQUEST =  'POST_UNLIKE_REQUEST';
export const POST_UNLIKE_SUCCESS =  'POST_UNLIKE_SUCCESS';
export const POST_UNLIKE_FAIL   =   'POST_UNLIKE_FAIL';

export const POST_SINGLE_REQUEST =  'POST_SINGLE_REQUEST';
export const POST_SINGLE_SUCCESS =  'POST_SINGLE_SUCCESS';
export const POST_SINGLE_FAIL   =   'POST_SINGLE_FAIL';

export const ADD_COMMENT_REQUEST =  'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS =  'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL  =    'ADD_COMMENT_FAIL';


export const DELETE_COMMENT_REQUEST =  'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS =  'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL  =    'DELETE_COMMENT_FAIL';