export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';

export const PROFILE_CURRENT_REQUEST = 'PROFILE_CURRENT_REQUEST';
export const PROFILE_CURRENT_SUCCESS = 'PROFILE_CURRENT_SUCCESS';
export const PROFILE_CURRENT_FAIL = 'PROFILE_CURRENT_FAIL';

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';


export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';

export const PROFILE_ADD_EXPERIENCE_REQUEST = 'PROFILE_ADD_EXPERIENCE_REQUEST';
export const PROFILE_ADD_EXPERIENCE_SUCCESS = 'PROFILE_ADD_EXPERIENCE_SUCCESS';
export const PROFILE_ADD_EXPERIENCE_FAIL = 'PROFILE_ADD_EXPERIENCE_FAIL';

export const PROFILE_ADD_EDUCATION_REQUEST = 'PROFILE_ADD_EXPERIENCE_REQUEST';
export const PROFILE_ADD_EDUCATION_SUCCESS = 'PROFILE_ADD_EXPERIENCE_SUCCESS';
export const PROFILE_ADD_EDUCATION_FAIL = 'PROFILE_ADD_EXPERIENCE_FAIL';

export const PROFILE_DELETE_EDUCATION_REQUEST = 'PROFILE_DELETE_EDUCATION_REQUEST';
export const PROFILE_DELETE_EDUCATION_SUCCESS = 'PROFILE_DELETE_EDUCATION_SUCCESS';
export const PROFILE_DELETE_EDUCATION_FAIL = 'PROFILE_DELETE_EDUCATION_FAIL';


export const PROFILE_DELETE_EXPERIENCE_REQUEST = 'PROFILE_DELETE_EXPERIENCE_REQUEST';
export const PROFILE_DELETE_EXPERIENCE_SUCCESS = 'PROFILE_DELETE_EXPERIENCE_SUCCESS';
export const PROFILE_DELETE_EXPERIENCE_FAIL = 'PROFILE_DELETE_EXPERIENCE_FAIL';